# Generated by Django 5.1.7 on 2025-04-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='emotion_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='emotion_value',
            field=models.FloatField(null=True),
        ),
    ]
